### ISSUE TITLE
Problem with sys.path on IDE in Windows

### ISSUE THREAD

**Issue by 000Zer000** [000Zer000/ZKit-Framework#10]
ZKit-Framework would break if user runs it from an IDE (tested on pycharm, VSCode)

Because these IDE take control of sys.path . zkit is unable to detect any payloads no matter builtin or user-payload . zkit should list payloads but it cant . 

 - OS: Windows (linux is not effected)
 - Python Version: 3.8.7
 - ZKit-Framework Version: All Versions effected

(I opened this issue to just dont forget this problem)

**Comment by Teraskull** [comment]
There is also an issue with updating, the function `deleverything` deletes the whole git repo.

**Comment by 000Zer000** [comment]
> There is also an issue with updating, the function `deleverything` deletes the whole git repo.

Im sorry but It is what its supposed to do . Just dont mind me

**Comment by 000Zer000** [comment]
Just take a look at the name of it `deleverything`

**Comment by Teraskull** [comment]
> Im sorry but It is what its supposed to do . Just dont mind me

Okay, but the issue is that after I test an update, it deletes the repo, and I can't push and pull anymore, I have to delete the folder manually, and then clone it again from github. It should delete only the `core` folder, and the python scripts. It should not delete the `.git` folder.

**Comment by 000Zer000** [comment]
> > Im sorry but It is what its supposed to do . Just dont mind me
> 
> Okay, but the issue is that after I test an update, it deletes the repo, and I can't push and pull anymore, I have to delete the folder manually, and then clone it again from github. It should delete only the `core` folder, and the python scripts. It should not delete the `.git` folder.

You are right but why should someone push or pull ???

**Comment by Teraskull** [comment]
Also, there is still a lot of functions, that don't work as planned. For example, `_export` still does not work. I will work on that.

**Comment by 000Zer000** [comment]
> Also, there is still a lot of functions, that don't work as planned. For example, `_export` still does not work. I will work on that.

there is no function named _export ?? What are you talking about ?????

**Comment by Teraskull** [comment]
> You are right but why should someone push or pull ???

First of all, contributors, not only end users will use this repo. Next, it is a bad practice to delete everything.

**Comment by 000Zer000** [comment]
> > You are right but why should someone push or pull ???
> 
> First of all, contributors, not only end users will use this repo. Next, it is a bad practice to delete everything.

Im down You are right

**Comment by Teraskull** [comment]
> there is no function named _export ?? What are you talking about ?????

Sorry, I meant `_extract`

**Comment by 000Zer000** [comment]
i think the function works . as i have seen the API.update and API.repair reference  to it not from self . Im updating it (right in the githubs editors)

**Comment by 000Zer000** [comment]
Now its updated

**Comment by Teraskull** [comment]
> Now its updated

Don't worry, I will test it, and make new Pull Requests with fixes, as there is a lot of stuff to refactor :)
I still didn't even touch the `core` folder.

**Comment by 000Zer000** [comment]
> > Now its updated
> 
> Don't worry, I will test it, and make new Pull Requests with fixes, as there is a lot of stuff to refactor :)
> I still didn't even touch the `core` folder.

Im happy that you are helping me . and one thing . please stop touching it becasue in newer release the whole directory tree have changed . so i cant merge your PR because it will break the code

**Comment by Teraskull** [comment]
> in newer release the whole directory tree have changed

Oh, I see, can you give the new tree details? I can help with the new version.

**Comment by Teraskull** [comment]
I won't touch `core`, but will help with the `updater.py` and `zkit.py` then.

**Comment by 000Zer000** [comment]
> I won't touch `core`, but will help with the `updater.py` and `zkit.py` then.

Thanks for your careness . (i know i have said this several times but you are helping me and i cant just use your help and ignore it)

**Comment by Teraskull** [comment]
> i cant just use your help and ignore it

Nah, don't worry, I like contributing and helping. Just notify me if there is anything important I shouldn't touch.

**Comment by 000Zer000** [comment]
> > in newer release the whole directory tree have changed
> 
> Oh, I see, can you give the new tree details? I can help with the new version.

Im releasing it now . (if i dont find any other bug) . but anyway thanks

**Comment by 000Zer000** [comment]
> > i cant just use your help and ignore it
> 
> Nah, don't worry, I like contributing and helping. Just notify me if there is anything important I shouldn't touch.

You can touch everything you want . im just saying that to make sure you dont touch anything that will may not be used . (if anything that i wrote looks offensive **dont mind me** my native language isnt english so my vocabulary is very limited )

**Comment by Teraskull** [comment]
> my native language isnt english so my vocabulary is very limited

I understand, don't worry, I'm not judging, only helping.

**Comment by 000Zer000** [comment]
Have you checked that update.py now works . (As you know i cant)

**Comment by Teraskull** [comment]
> Have you checked that update.py now works . (As you know i cant)

I will work on it. As I said, what is `source`?

`self._extract(source, PATH)`

**Comment by 000Zer000** [comment]
a broken mechanizm . as surely you have seen there is a function named `_download_version`. that downloads the version and returns the path . (or was) . with new change it doesnt return any and saves it to `self.sourcepath` it was supposed to be self.sourcepath after changes but havent changed

**Comment by 000Zer000** [comment]
Fixed :)

**Comment by 000Zer000** [comment]
Newer release . please pay attention to the changes in the directory tree . i think now you understood why i said to dont touch core (i guess) Just dont mind me

**Comment by 000Zer000** [comment]
Any idea how to fix the problem that i opened this issue . (problem with path on some IDE's) ??

**Comment by Teraskull** [comment]
> Any idea how to fix the problem that i opened this issue . (problem with path on some IDE's) ??

I will look into that and see what I can do.

**Comment by 000Zer000** [comment]
> > Any idea how to fix the problem that i opened this issue . (problem with path on some IDE's) ??
> 
> I will look into that and see what I can do.

Thanks !

**Comment by 000Zer000** [comment]
I have fixed it . Thanks because of your help . you have helped a lot in updater.py, and my mistakes in english
