### ISSUE TITLE
wanted

### ISSUE THREAD

**Issue by dubna48k** [000Zer000/ZKit-Framework#2]
I want to test your code, where can I see it?

**Comment by 000Zer000** [comment]
thnaks for your attention.  if you have projects on github and solo you know how hard it is . you and walter are requested now , if it reaches 10 . we can have it back . all of these have a reason the reason is i want to give you the best project .

**Comment by 000Zer000** [comment]
if you really want it email too me

**Comment by 000Zer000** [comment]
so i can send you the source code

**Comment by 000Zer000** [comment]
i will maintain it again . reverting back to commit . after  source code is on github

**Comment by 000Zer000** [comment]
closing this issue
