### ISSUE TITLE
Issues with Banner

### ISSUE THREAD

**Issue by damian2601** [000Zer000/ZKit-Framework#3]
Rename at line 17 "from Banners" to "from ZKit_Banners" because the console give output "No module named 'Banners' "
Thank you 
(Tested on Windows)

**Comment by 000Zer000** [comment]
Thanks for supporting this project . im releasing new update for it . i have found that issue and fixed it

**Comment by 000Zer000** [comment]
im closing it . i hope you enjoy using it

**Comment by 000Zer000** [comment]
if your problem didnt get fixed in new version . notify me to reopen this issue
