### ISSUE TITLE
Issue with zkit.py

### ISSUE THREAD

**Issue by ayashgupta** [000Zer000/ZKit-Framework#6]
The program is not opening. Whenever I try to open it, it automatically closes and goes back to the directory. 
Enclosing screenshot for the same. 
![zkit](https://user-images.githubusercontent.com/69060432/89824475-ccfa5780-db70-11ea-95b5-849e2027b50a.JPG)

**Comment by 000Zer000** [comment]
hi thanks for opening this issue . where does it gets closed ? before getting run or at updater . or when you choose a number from the menu

**Comment by 000Zer000** [comment]
im sorry but i cant see the screenshot . (bad internet)

**Comment by 000Zer000** [comment]
strange it happens for me too , checking for problem . if i found it i will update it

**Comment by 000Zer000** [comment]
Commited the change to zkit.py . i have several backups . and i accidently pushed one of backups . (4 are available) so the problem was fixed in the other i wanted to push . now its fixed . if its happening again . let me know . 

Have Fun !

**Comment by ayashgupta** [comment]
Thanks! I am kind of a fan for Z-Kit, so, I keep my eye on every release!

**Comment by ayashgupta** [comment]
It is still giving some error. 
Please have a look. 

Sth went really wrong that we couldnt handle it
the exceptions value have saved to Errors.log
please report this on github to me.Do you want zkit to reraise it ? (reraising may help better) (Y/N): ^CTraceback (most recent call last):
![zkit](https://user-images.githubusercontent.com/69060432/89834292-2d44c580-db80-11ea-8521-d5f14efcc9c6.JPG)

**Comment by 000Zer000** [comment]
Now its getting real . can i ask for some information . Its looks you are using Kali . i have tested it on kali and ubuntu . 
but which version of python are you using ? is you kali old ? could you write the data in Errors.log . (as i have wrote in the crash handler) . 
The most important info that you can give me to solve this issue . 

1. Data in Errors.log

2. Your python version . 

if you please choose Y when asks for rerasing it and give me these info . i cant do such a thing without these info . 

Thanks

**Comment by 000Zer000** [comment]
> Thanks! I am kind of a fan for Z-Kit, so, I keep my eye on every release!

Thanks bro . this world needs good guys like you . 
Cheers and Have Fun !

**Comment by 000Zer000** [comment]
I have commited a fix . that i find when searching for bug . if it is not yours . please write info in Errors.log and your python version .
if it is fixed with that commit . i will happily work on another version

A BIG THANKS for reporting this bug.

Have Fun !

**Comment by 000Zer000** [comment]
If your issue is fixed please close this issue . if you have any request for adding anything to zkit . Im all at service (on other issue) . other bugs found ? i will be happy to respond to a new issue . 

Have Fun !

**Comment by 000Zer000** [comment]
Im closing it . If you problem still exists you can repopen it , or just open another issue . 

Have Fun !

**Comment by ayashgupta** [comment]
Initalizing updater
Checking for updates...Done
Your are using the latest version (1.4.6)
                                         Hacking is C O L O R F U L 
Available Options Are :
  {1} --> Create A RootKit
  {2} --> Create A Ransomware
  {3} --> Create A KeyLogger 
  {4} --> Run A Dos Attack
  {5} --> Connect To A Victim
  {6} --> Generate Your User Payloads
  {000}--> Exit ZKit-Framework

Sth went really wrong that we couldnt handle it
the exceptions value have saved to Errors.log
please report this on github to me.Do you want zkit to reraise it ? (reraising may help better) (Y/N): Y
This is going to print full error . please report it on github
Traceback (most recent call last):
  File "zkit.py", line 106, in <module>
    crash_handler(e)
  File "zkit.py", line 104, in <module>
    Start().mainloop() #issue #6 missing running the main_loop
AttributeError: 'Start' object has no attribute 'mainloop'


This is what I got after pressing Y

and I am using the latest version of Kali and a run it by typing python3 zkit.py

**Comment by ayashgupta** [comment]
[2020-08-11 14:44:25.615636] : 'Start' object has no attribute 'mainloop'

**Comment by 000Zer000** [comment]
please use the latest version . 1.4.7 and see if it is fixed or not

**Comment by 000Zer000** [comment]
please see if your issue has been fixed or not . if yes please close this issue . if not let me know to search for the bug 

Have Fun !

**Comment by 000Zer000** [comment]
im really thanking you because of times you tried to run it and it got an error . a big thanks
another thanks because of showing the data in errors.log . i found the bug from there .

**Comment by ayashgupta** [comment]
Hey, not a problem! 
I am getting this error now. It is not even starting up. 
Traceback (most recent call last):
  File "zkit.py", line 14, in <module>
    from core.helper_core import notify, Color, Generate, dos, \
  File "/opt/ZKit-Framework/core/helper_core/__init__.py", line 10, in <module>
    from core.helper_core._core import * # NOQA
  File "/opt/ZKit-Framework/core/helper_core/_core.py", line 97
    <<<<<<< HEAD
    ^
SyntaxError: invalid syntax

**Comment by 000Zer000** [comment]
i thought i deleted these . strange . it happens because im pushing code from git (command line) . `git pull` . i dont know why these happen . let me fix it

**Comment by 000Zer000** [comment]
please wait 2 minutes (i mean really 2 minutes) . Im debugging the program . (damn pull)

Have Fun !

**Comment by 000Zer000** [comment]
please now download the source from master and see if it is happening again or not .

**Comment by ayashgupta** [comment]
It is now opening, however, after typing in the option, for example, 1 or any other option, it is giving the following error:

{000} --> Back To Main Menu
Please Choose One Of Them (Number Of It): 1
Sth went really wrong that we couldnt handle it
the exceptions value have saved to Errors.log
please report this on github to me.Do you want zkit to reraise it ? (reraising may help better) (Y/N): Y 
This is going to print full error . please report it on github
Traceback (most recent call last):
  File "zkit.py", line 108, in <module>
    crash_handler(e)
  File "zkit.py", line 106, in <module>
    starter.main_loop()
  File "zkit.py", line 101, in main_loop
    self.execute(choice)
  File "zkit.py", line 82, in execute
    self._execute_payload_related(choice)
  File "zkit.py", line 78, in _execute_payload_related
    list_builtin_payloads_helper(choice)
  File "zkit.py", line 31, in list_builtin_payloads_helper
    Generate(list(payloads.values())[int(index) - 1])
IndexError: list index out of range

**Comment by 000Zer000** [comment]
Did you chose user payload (6) . if yes look at choices that are available  . like you havent installed any. user-payloads are like plugins . [Toturial](https://github.com/000Zer000/ZKit-Framework/wiki/Creating-My-Own-Payload)

**Comment by ayashgupta** [comment]
I only run it normally. I just use python3 zkit.py 
And the options showed up, I typed in 1 first and it gave me the above error. Afterwards, I started it again and typed 3 and received the same error again.

**Comment by 000Zer000** [comment]
could you take a video from the moment you start the termianl until the error and send it to my email ?

**Comment by 000Zer000** [comment]
if a picture worths hundered words a video worths millions

**Comment by ayashgupta** [comment]
Sure.

**Comment by 000Zer000** [comment]
i tested the newest release (1.4.7) on windows and on linux (kali) . No issue it can generate it very well .

Lets anylize the error text you have shared with me

LINE 1 : `{000} --> Back To Main Menu` . no other choices are available . only exiting . (looks like you are in user_payload generator (choice 6) in the first menu or cutting the error for making it shorter)

LINE 2 : `Please Choose One Of Them (Number Of It): 1` you have entered 1 . zkit asked about the number of payload . its impossible for zkit to print this because its not just a text . mechanizm behind it (more looks like you are in user-payload generator choice 6)

LINE 3 - 5 : Crash handler

Nothing important until : 
```
list_builtin_payloads_helper(choice)
File "zkit.py", line 31, in list_builtin_payloads_helper
Generate(list(payloads.values())[int(index) - 1])
IndexError: list index out of range
```
list builtin_payloads_helper says that the payload type was builtin . "what that deosnt match" with LINE 1 

this means nor your information is correct . (changed error) for example shortening the error . errors never lie so it was builtin payload . 

my error log when entering a valid menu (keylogger) and entering wrong index at keylogger menu

```
{1} --> keylogger_gmail >>> \core\lib\payloads\keylogger\keylogger_gmail

{2} --> keylogger_tcp   >>> \core\lib\payloads\keylogger\keylogger_tcp

{3} --> keylogger_udp   >>> \core\lib\payloads\keylogger\keylogger_udp

{000} --> Back To Main Menu
Please Choose One Of Them (Number Of It): 111111
Sth went really wrong that we couldnt handle it
the exceptions value have saved to Errors.log
please report this on github to me.Do you want zkit to reraise it ? (reraising may help better) (Y/N): Y
This is going to print full error . please report it on github
Traceback (most recent call last):
  File "z:/The ZKit Project/Framework/zkit.py", line 108, in <module>
    crash_handler(e)
  File "z:/The ZKit Project/Framework/zkit.py", line 106, in <module>
    starter.main_loop() #issue #6 missing running the main_loop
  File "z:/The ZKit Project/Framework/zkit.py", line 101, in main_loop
    self.execute(choice)
  File "z:/The ZKit Project/Framework/zkit.py", line 82, in execute
    self._execute_payload_related(choice)
  File "z:/The ZKit Project/Framework/zkit.py", line 78, in _execute_payload_related
    list_builtin_payloads_helper(choice)
  File "z:/The ZKit Project/Framework/zkit.py", line 31, in list_builtin_payloads_helper
    Generate(list(payloads.values())[int(index) - 1])
IndexError: list index out of range
```
My error is the same with you if we cut the places you have cutted . i mean (from menu until the payload menu)
i have entered a wrong index (111111) so it was not possible for zkit to handle it . because 111111th payload doesnt exist



AT END : WHAT HAPPEND .

Nor the error is modified (for shortening it) . nor using user payload . but you havent installed any. 
**This was what i understood from the error . they might be wrong .**

I have not seen the video . but it was my analize from the error text

Im really happy you are helping me solve this issue

**Comment by 000Zer000** [comment]
> Sure.

Thanks

**Comment by ayashgupta** [comment]
I have sent it, please have a look! 
and I really like what you are doing, so, I can help in something good! :)

**Comment by 000Zer000** [comment]
> I have sent it, please have a look!
> and I really like what you are doing, so, I can help in something good! :)

Thank you . i have seen what is happening . let me analyze it

**Comment by 000Zer000** [comment]
POSSIBLE PROBLEM . could you go to . `ZKit-Framework/core/lib/payloads/rootkit/' and run `ls -a` write down the result .

**Comment by ayashgupta** [comment]
root@kali:/opt/ZKit-Framework/core/lib/payloads/rootkit# ls -a
.  ..  ft_tcp  ft_udp  reverse_tcp  reverse_udp

**Comment by 000Zer000** [comment]
> root@kali:/opt/ZKit-Framework/core/lib/payloads/rootkit# ls -a
> . .. ft_tcp ft_udp reverse_tcp reverse_udp

Thanks . i though . you have a corrupted version of zkit . but no . 

I will be happy if you help me and run this at zkit root (the zkit-framework folder)

```
python3
```
now you are in python interpreter then run : 

```
import os 
r, d, f = os.walk('core/lib/payloads/rootkit')
print(r)
print(d)
print(f)
```

i want to test if os.walk is working .

**Comment by ayashgupta** [comment]
>>> import os
>>> r, d, f = os.walk('core/lib/payloads/rootkit')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: too many values to unpack (expected 3)

**Comment by ayashgupta** [comment]
getting this instead.

**Comment by 000Zer000** [comment]
sorry . i forgot that . please run this instead . 

```python
import os 
for r, d, f  in os.walk('core/lib/payloads/rootkit'):
    print(r)
    print(d)
    print(f)
```
really sorry it was very old i forgot the syntax

**Comment by ayashgupta** [comment]
>>> import os
>>> for r, d, f  in os.walk('core/lib/payloads/rootkit'):
...     print(r)
...     print(d)
...     print(f)
... 
core/lib/payloads/rootkit
['ft_tcp', 'reverse_udp', 'ft_udp', 'reverse_tcp']
[]
core/lib/payloads/rootkit/ft_tcp
[]
['linux.py', 'zkit.yml', 'windows.py']
core/lib/payloads/rootkit/reverse_udp
[]
['linux.py', 'zkit.yml', 'windows.py']
core/lib/payloads/rootkit/ft_udp
[]
['linux.py', 'zkit.yml', 'windows.py']
core/lib/payloads/rootkit/reverse_tcp
[]
['linux.py', 'zkit.yml', 'windows.py']
>>> 
>>>

**Comment by 000Zer000** [comment]
oh god,  things got more complicated .

**Comment by ayashgupta** [comment]
Lol, in the mean time, if you don't mind, can you generate a keylogger for me? I need it urgently and would have to send it attached to a ppt tomorrow without letting the person know. (Testing on friend's computer)

**Comment by 000Zer000** [comment]
yes i will generate one but which keylogger (tcp, udp, gmail) if tcp or udp your hostname and an open port if gmail your gmail with the password (send password to me on email) . and for inserting the exe (you can compile it using pyinstaller) like this : 

follow these instructes : 

Click Insert > Object. Select Create from file.
Click Browse and look for the exe file. Click Ok.
Now, click Slide Show > Custom Animation.
Select the exe icon that has been inserted, click Add Effect > Object
Actions > Activate Contents. Under Start, set On click to After Previous so
that it starts automatically.

But when user runs the powerpoint will recieve an warning . so extend the python file to for example open a picture or play an audio . so your friend doesnt understand anything . compile it and name it like "PowepointMusicPlayer.exe" so they will piss the warning off

**Comment by 000Zer000** [comment]
send details to me on my email and recieve the payload there . just dont run it .

Use it legally and Have Fun !

**Comment by ayashgupta** [comment]
I have sent the mail. 
Thank you!

**Comment by ayashgupta** [comment]
> send details to me on my email and recieve the payload there . just dont run it .
> 
> Use it legally and Have Fun !

Can I test in on my computer first?

**Comment by 000Zer000** [comment]
> > send details to me on my email and recieve the payload there . just dont run it .
> > Use it legally and Have Fun !
> 
> Can I test in on my computer first?

I dont recommend . because you will get problem with removing it 

Have Fun !

**Comment by 000Zer000** [comment]
Please close this or i will close it after some time . you have helped me very well .

**Comment by ayashgupta** [comment]
You are welcome! You have helped me a lot! 
I tried to run the py file that you sent, however, I am not receiving any mails from the keylogger. Also, I am kind of noob in using python, can you please guide me on how to compile it using pyinstaller? Please?

And also, from this step, 
_Now, click Slide Show > Custom Animation.
Select the exe icon that has been inserted, click Add Effect > Object
Actions > Activate Contents. Under Start, set On click to After Previous so
that it starts automatically._

I am not able to understand as their is no option such as custom animation in slideshow.

**Comment by 000Zer000** [comment]
It was shiny as diomand that will not run . at first i should run UAC (that pyinstaller with flag --uac-admin will) then it shows itself as system . so it looks like a part of windows . so windows only uses the binary so it have to be compiled to exe to run (if you have ever read README i have said that windows payloads wont run unless you compile them to exe
For sure . i have built this project for helping people . 

if your OS  is windows . you can else you need an windows os to compile it to exe . 

if you have windows 

run 

```
pip install pyinstaller
```
to install pyinstaller .

then run 

```
pyinstaller --onefile --uac-admin --clean -w THEKEYLOGGER.py 
```
wait for it to finish . after that enter the place you started the terminal and you will see a folder was added "dist" enter it and 
you see an exe in it .

BOOM ! 

and about the powerpoint i dont remember exactly play with it a bit . (i forgot the menus)

it wont work without the --uac-admin flag . (dont email me , it will be counted as spam when you do it alot) 

And about the keylogger . it will send it from the gmail you entered to the gmail your entered .

**Comment by ayashgupta** [comment]
I have done everything as you said, got an error which said "Failed to execute script key"

**Comment by 000Zer000** [comment]
C'mon . full error . full

**Comment by ayashgupta** [comment]
That was just a pop up I received after executing the compiled exe file. 

(Just a quesion, doest it run even after system restarts?"

**Comment by ayashgupta** [comment]
I guess my computer is corrupt if the files are running fine into your computer. lol

**Comment by 000Zer000** [comment]
if it deploys yes , else no . for that problem i cant answer you as developer i can answer you as a friend

**Comment by 000Zer000** [comment]
it woks very great on my system . i have tested them before publishing

**Comment by ayashgupta** [comment]
Answer me as a friend then! :)
Where am I getting wrong!?
I tried to compile it, it compiled without any issue. 

I run it, it gives a pop up with Failed to execute script. 

I am so sorry but it is just like I am having too much expectations from this. Sorry brother!

**Comment by 000Zer000** [comment]
as i have read . it looks like it you dont have pynput installed . so you need pynput because pyinstaller is suppossed to bundle python scripts into exe not to generate code 
install is using 

```
pip install pynput
```
then compile again

**Comment by 000Zer000** [comment]
> Answer me as a friend then! :)
> Where am I getting wrong!?
> I tried to compile it, it compiled without any issue.
> 
> I run it, it gives a pop up with Failed to execute script.
> 
> I am so sorry but it is just like I am having too much expectations from this. Sorry brother!

i said that because im not a developer in pyinstaller . just a user like you . so i cant (not i dont want) give you the problem fixes that a pyinstaller developer can

**Comment by 000Zer000** [comment]
im in troble . later bro

**Comment by ayashgupta** [comment]
Sure, it didn't run after this as well. Thankyou so much for your time and I hope this works in the future. :)
Have fun!

**Comment by 000Zer000** [comment]
Im sorry . me and my friends were annoying our teacher (an easy prank) .  . because i was a part of it . when doing the project . i was doing two things . working on project with my friends and solving this issue . the time i said `im in troble . later bro` it was near for us to get caught . so i had to pack my things and run . Anyway . 

i have tested all the payload . if you compile it using `--uac-admin`flag . and  have things that it needs (i mean having pynput) it will without any problem 

You too !

**Comment by 000Zer000** [comment]
I have found why ZKit was unable to find payloads . i will do a commit after that it will be fixed
